name: pdejax
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip

  # Numeric + Sci
  - numpy
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - h5py
  - ffmpeg
  # Dev & tooling
  - pytest
  - jupyter
  - ipykernel
  - typer
  - pip:
      - torch
      - torchvision
      - torchaudio
      - "jax[cuda12]"
      - jaxlib
      - phiflow